import React from 'react';

import { SvgBook, SvgLogo, SvgHeart, SvgPhoto, SvgDiscord } from './svg'
import { Container, Row_CenterCSS, Col_CenterCSS, HoverCSS } from './styled'
import styled, { css } from 'styled-components';


const version = 'v.0.1'


function MenuInfo() {
    return (
      <Container>
        <Col_A_Center_Gap16>
          <SvgBook></SvgBook>
          <Col_A_Center>
            <SvgLogo></SvgLogo>
            <Div>{version}</Div>
          </Col_A_Center>
        </Col_A_Center_Gap16>

        <P>
          Enterpix is an AI-Generated Image Search Engine.<br/>
          Get inspired by creative artworks generated by<br/>
          Midjourney, DALLE2, Stable-diffusion and more.
        </P>

        <Col_A_Center_Gap6>
          <Row_A_Center>
            <SvgHeart></SvgHeart>
            <Span>
              Add your favorite images and prompts to your collection.
            </Span>
          </Row_A_Center>
          <Row_A_Center>
            <SvgPhoto></SvgPhoto>
            <Span>
              Generate your own image of your imagination.
            </Span>
          </Row_A_Center>
        </Col_A_Center_Gap6>

        <Col_A_Center>
          <Button>
            <A target="_blank" href="https://enterpix.app/">Visit Enterpix</A>
          </Button>
          <Button className="bg-white">
            <SvgDiscord></SvgDiscord>
            <A target="_blank" href="https://discord.com/invite/bR4eHzpcvQ">Join Community</A>
          </Button>
        </Col_A_Center>

        <Row_Center_Gap48>
          <a target="_blank" href="https://enterpix.app/terms-and-conditions">Terms</a>
          <a target="_blank" href="https://enterpix.app/privacy-policy">Privacy Policy</a>
        </Row_Center_Gap48>
      </Container>
    )
}


const Col_A_Center = styled.div`
  ${Col_CenterCSS}
  justify-content: flex-start;
`

const Col_A_Center_Gap16 = styled.div`
  ${Col_CenterCSS}
  justify-content: flex-start;
  padding-top: 16px;
  gap: 16px;
`

const Col_A_Center_Gap6 = styled.div`
  ${Col_CenterCSS}
  justify-content: flex-start;
  gap: 6px;
`

const Row_A_Center = styled.div`
  ${Row_CenterCSS}
  justify-content: flex-start;

  padding: 6px;
  gap: 6px;
  
  width: 368px;
  height: 44px;
  
  background: #F9FAFB;
  
  border: 1px solid #F3F4F6;
  border-radius: 16px;
`

const Row_Center_Gap48 = styled.div`
  ${Row_CenterCSS}
  gap: 48px;

  a {
    ${HoverCSS}
    font-family: 'Pretendard';
    font-style: normal;
    font-weight: 500;
    font-size: 12px;
    line-height: 16px;

    text-decoration-line: underline;
    color: #9CA3AF;
  }

`

const Div = styled.div`
  font-family: 'Pretendard';
  font-style: normal;
  font-weight: 600;
  font-size: 24px;
  line-height: 32px;
  
  text-align: center;
  
  color: #000000;
`

const Button = styled.button`
  ${Row_CenterCSS}
  ${HoverCSS}
  border-radius: 12px;
  box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05);
  transition: 0.15s;

  
  &:not(.bg-white) {
    width: 228px;
    height: 36px;
  
    background: #6D7DFD;
    border: 0;
  
    a {
      color: white;
    }
  }
  
  &.bg-white {
    width: 227px;
    height: 36px;
  
    background: #FFFFFF;
    border: 1px solid #D1D5DB;
  
    a {
      color: #111827;
    }
  }
`

const P = styled.p`
  margin: 0;
  font-family: 'Pretendard';
  font-style: normal;
  font-weight: 600;
  font-size: 14px;
  line-height: 21px;
  
  text-align: center;

  color: #000000;
`

const Span = styled.span`
  font-family: 'Pretendard';
  font-style: normal;
  font-weight: 500;
  font-size: 12px;
  line-height: 16px;
  
  color: #6B7280;
`

const A = styled.a`
  cursor: pointer;
  text-decoration: none;
`

export default MenuInfo